Major revisions to the build scripts. Now everything can be built using "msbuild msfast.proj /t:createinstaller". This will build the solution and build the installer. Pulled in Watin's utility class to clear cache due to getting the exception below on my own box. Watin's utility class is pretty stable so this should work better.
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at MySpace.MSFast.SysImpl.Win32.InternetExplorer.TestBrowser.BrowserCacheHelper.DeleteUrlCacheEntry(IntPtr lpszUrlName)
   at MySpace.MSFast.SysImpl.Win32.InternetExplorer.TestBrowser.BrowserCacheHelper.ClearCache(Object state) in c:\Source\msfast\src\MySpace.MSFast.SysImpl.Win32.InternetExplorer\TestBrowser\BrowserCacheHelper.cs:line 215
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)